# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eisbaer1832/projects/subsis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eisbaer1832/projects/subsis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eisbaer1832/projects/subsis/CMakeFiles /home/eisbaer1832/projects/subsis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eisbaer1832/projects/subsis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named subsis

# Build rule for target.
subsis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subsis
.PHONY : subsis

# fast build rule for target.
subsis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/build
.PHONY : subsis/fast

backends/imgui.o: backends/imgui.cpp.o
.PHONY : backends/imgui.o

# target to build an object file
backends/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui.cpp.o
.PHONY : backends/imgui.cpp.o

backends/imgui.i: backends/imgui.cpp.i
.PHONY : backends/imgui.i

# target to preprocess a source file
backends/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui.cpp.i
.PHONY : backends/imgui.cpp.i

backends/imgui.s: backends/imgui.cpp.s
.PHONY : backends/imgui.s

# target to generate assembly for a file
backends/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui.cpp.s
.PHONY : backends/imgui.cpp.s

backends/imgui_demo.o: backends/imgui_demo.cpp.o
.PHONY : backends/imgui_demo.o

# target to build an object file
backends/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_demo.cpp.o
.PHONY : backends/imgui_demo.cpp.o

backends/imgui_demo.i: backends/imgui_demo.cpp.i
.PHONY : backends/imgui_demo.i

# target to preprocess a source file
backends/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_demo.cpp.i
.PHONY : backends/imgui_demo.cpp.i

backends/imgui_demo.s: backends/imgui_demo.cpp.s
.PHONY : backends/imgui_demo.s

# target to generate assembly for a file
backends/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_demo.cpp.s
.PHONY : backends/imgui_demo.cpp.s

backends/imgui_draw.o: backends/imgui_draw.cpp.o
.PHONY : backends/imgui_draw.o

# target to build an object file
backends/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_draw.cpp.o
.PHONY : backends/imgui_draw.cpp.o

backends/imgui_draw.i: backends/imgui_draw.cpp.i
.PHONY : backends/imgui_draw.i

# target to preprocess a source file
backends/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_draw.cpp.i
.PHONY : backends/imgui_draw.cpp.i

backends/imgui_draw.s: backends/imgui_draw.cpp.s
.PHONY : backends/imgui_draw.s

# target to generate assembly for a file
backends/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_draw.cpp.s
.PHONY : backends/imgui_draw.cpp.s

backends/imgui_impl_glfw.o: backends/imgui_impl_glfw.cpp.o
.PHONY : backends/imgui_impl_glfw.o

# target to build an object file
backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_glfw.cpp.o
.PHONY : backends/imgui_impl_glfw.cpp.o

backends/imgui_impl_glfw.i: backends/imgui_impl_glfw.cpp.i
.PHONY : backends/imgui_impl_glfw.i

# target to preprocess a source file
backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_glfw.cpp.i
.PHONY : backends/imgui_impl_glfw.cpp.i

backends/imgui_impl_glfw.s: backends/imgui_impl_glfw.cpp.s
.PHONY : backends/imgui_impl_glfw.s

# target to generate assembly for a file
backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_glfw.cpp.s
.PHONY : backends/imgui_impl_glfw.cpp.s

backends/imgui_impl_opengl3.o: backends/imgui_impl_opengl3.cpp.o
.PHONY : backends/imgui_impl_opengl3.o

# target to build an object file
backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_opengl3.cpp.o
.PHONY : backends/imgui_impl_opengl3.cpp.o

backends/imgui_impl_opengl3.i: backends/imgui_impl_opengl3.cpp.i
.PHONY : backends/imgui_impl_opengl3.i

# target to preprocess a source file
backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_opengl3.cpp.i
.PHONY : backends/imgui_impl_opengl3.cpp.i

backends/imgui_impl_opengl3.s: backends/imgui_impl_opengl3.cpp.s
.PHONY : backends/imgui_impl_opengl3.s

# target to generate assembly for a file
backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_impl_opengl3.cpp.s
.PHONY : backends/imgui_impl_opengl3.cpp.s

backends/imgui_tables.o: backends/imgui_tables.cpp.o
.PHONY : backends/imgui_tables.o

# target to build an object file
backends/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_tables.cpp.o
.PHONY : backends/imgui_tables.cpp.o

backends/imgui_tables.i: backends/imgui_tables.cpp.i
.PHONY : backends/imgui_tables.i

# target to preprocess a source file
backends/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_tables.cpp.i
.PHONY : backends/imgui_tables.cpp.i

backends/imgui_tables.s: backends/imgui_tables.cpp.s
.PHONY : backends/imgui_tables.s

# target to generate assembly for a file
backends/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_tables.cpp.s
.PHONY : backends/imgui_tables.cpp.s

backends/imgui_widgets.o: backends/imgui_widgets.cpp.o
.PHONY : backends/imgui_widgets.o

# target to build an object file
backends/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_widgets.cpp.o
.PHONY : backends/imgui_widgets.cpp.o

backends/imgui_widgets.i: backends/imgui_widgets.cpp.i
.PHONY : backends/imgui_widgets.i

# target to preprocess a source file
backends/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_widgets.cpp.i
.PHONY : backends/imgui_widgets.cpp.i

backends/imgui_widgets.s: backends/imgui_widgets.cpp.s
.PHONY : backends/imgui_widgets.s

# target to generate assembly for a file
backends/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/backends/imgui_widgets.cpp.s
.PHONY : backends/imgui_widgets.cpp.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subsis.dir/build.make CMakeFiles/subsis.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... subsis"
	@echo "... backends/imgui.o"
	@echo "... backends/imgui.i"
	@echo "... backends/imgui.s"
	@echo "... backends/imgui_demo.o"
	@echo "... backends/imgui_demo.i"
	@echo "... backends/imgui_demo.s"
	@echo "... backends/imgui_draw.o"
	@echo "... backends/imgui_draw.i"
	@echo "... backends/imgui_draw.s"
	@echo "... backends/imgui_impl_glfw.o"
	@echo "... backends/imgui_impl_glfw.i"
	@echo "... backends/imgui_impl_glfw.s"
	@echo "... backends/imgui_impl_opengl3.o"
	@echo "... backends/imgui_impl_opengl3.i"
	@echo "... backends/imgui_impl_opengl3.s"
	@echo "... backends/imgui_tables.o"
	@echo "... backends/imgui_tables.i"
	@echo "... backends/imgui_tables.s"
	@echo "... backends/imgui_widgets.o"
	@echo "... backends/imgui_widgets.i"
	@echo "... backends/imgui_widgets.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

